version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    command: >
      sh -c "
        while ! pg_isready -h db -p 5432 -U postgres; do
          sleep 1;
        done;

        flask db upgrade &&
        gunicorn --bind 0.0.0.0:5000 app:app
      "

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  seed:
    build: .
    depends_on:
      - db
      - web
    volumes:
      - .:/app
    command: >
      sh -c "
        while ! pg_isready -h db -p 5432 -U postgres; do
          sleep 1;
        done;

        sleep 5;

        python scripts/seed_db.py
      "
    profiles:
      - seed

volumes:
  postgres_data: